Actions/urls.py
"""Django Module(s)"""
from django.urls import path

from . import views

urlpatterns = [
    path('customers/', views.Customers.as_view(), name='kunden_list'),
    path("customers/<int:nr>/", views.CustomerDV.as_view(), name="customer_detail"),
    path('actions/', views.Actions.as_view(), name='action_list'),
    path("actions/<int:id>/", views.ActionDV.as_view(), name="action_detail"),
    path('pay-in/',views.pay_in),
    path('pay-out/', views.pay_out),
    path('settings/', views.Settings.as_view())
]

StadtBank/urls.py
"""Django Module(s)"""
from django.contrib import admin
from django.urls import include, path

from Actions import views as urls

urlpatterns = [
    path('', urls.index),
    path('', include("Actions.urls")),
    path('admin/', admin.site.urls),
    path("__debug__/", include("debug_toolbar.urls")), #DEBUG
]

Actions/models.py
"""Django Module(s)"""
from django.db import models


class Customer(models.Model):
    """Customer Class"""
    nr = models.IntegerField(primary_key=True)
    name = models.TextField()
    balance = models.ImageField()

    def __str__(self) -> str:
        return f"{self.name}"

    class Meta:
        """Customer.Meta Class"""
        db_table = 'customers'


class Action(models.Model):
    """Action Class"""
    id = models.AutoField(primary_key=True)
    nr = models.IntegerField()
    date = models.DateTimeField(auto_now_add=True)
    type = models.TextField(choices=[('payin', 'Pay In'),
                                           ('payout', 'Pay Out'),
                                           ('transfer', 'Transfer')])
    amount = models.FloatField()
    related_nr = models.IntegerField(null=True)

    def __str__(self):
        return f"Action {self.id}"

    class Meta:
        """Action.Meta Class"""
        db_table = 'actions'

Actions/forms.py
"""Django Module(s)"""
from django import forms

class CustomerF(forms.Form):
    """Customer From"""
    nr = forms.IntegerField(label="Customer Nr")
    amount = forms.FloatField()

Actions/views.py
"""Django Module(s)"""
from django.http import Http404, HttpResponseRedirect #HttpResponse,
from django.shortcuts import render, get_object_or_404
from django.views import View

from Actions.models import Customer, Action
from .forms import CustomerF

# Create your views here.
# pylint: disable=no-member

def index(request):
    """Index Page"""
    customers = Customer.objects.all()
    actions = Action.objects.all()
    return render(request, 'dashboard.html', {'customers': customers, 'actions': actions})


class Actions(View):
    """Actions Page"""
    def get(self, request):
        """Actions.get"""
        transaktionen = Action.objects.all()
        return render(request, 'actions.html', {'actions': transaktionen})


class Customers(View):
    """Customers Page"""
    def get(self, request):
        """Customers.get"""
        kunden = Customer.objects.all()
        return render(request, 'customers.html', {'customers': kunden})



class CustomerDV(View):
    """Customer Detail View page"""
    #ID, Numer, Date, Type, Balance

    def get(self, request, nr):
        """CustomerDV.get"""
        try:
            customer = get_object_or_404(Customer, nr=nr)
            saldo = customer.balance
            name = customer.name

            actions = Action.objects.filter(nr=nr)

            table = []
            if actions:
                table = actions.values_list(
                    'id', 'nr', 'date', 'type', 'amount')

            data = {"nr": nr, "name": name, "saldo": saldo}

            return render(request, 'customer.html', {'main': data, 'actions': table})
        except Http404:
            # Handle the case when no Transaktionen object is found
            return render(request, '404.html')



class ActionDV(View):
    """Action Detail View page"""
        #ID, Numer, Date, ActionType, amount, related_nr

    def get(self, request, id):
        """ActionDV.get"""
        try:
            action = get_object_or_404(Action, id=id)
            ammount = action.amount 
            customer = get_object_or_404(Customer,nr=action.nr)
            date = action.date
            actiontype = action.type
            releated_nr = action.related_nr

            return render(request, 'action.html', {'id': id, 'nr': action.nr, 'customer': customer, 'date': date, 'type': actiontype, 'releated': releated_nr})
        except Http404:
            # Handle the case when no Transaktionen object is found
            return render(request, '404.html')


def pay_in(request):
    """payIn API"""

    if request.method == "POST":
        form = CustomerF(request.POST)

        if form.is_valid():
            datas = form.cleaned_data
            target = Customer.objects.get(nr=datas["nr"])
            target.balance += datas["amount"]
            target.save()

            action = Action(
                nr=datas["nr"], actiontype="payin", amount=datas["amount"])
            action.save()

        else:
            print("NotValid")

    return HttpResponseRedirect("/.")

def pay_out(request):
    """PayOut API"""

    if request.method == "POST":
        form = CustomerF(request.POST)

        if form.is_valid():
            datas = form.cleaned_data
            target = Customer.objects.get(nr=datas["nr"])
            target.balance -= datas["amount"]
            target.save()

            action = Action(
                nr=datas["nr"], actiontype="payout", amount=datas["amount"])
            action.save()

        else:
            print("NotValid")

    return HttpResponseRedirect("/.")


class Settings(View):
    """Settings Page"""
    def get(self, request):
        """Settings.get"""
        return render(request, 'settings.html')

Actions/templates/action.html
<!DOCTYPE html>
<html>
<head>
    <title>Action ({{main.nr}}/{{main.name}})</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'style.css' %}" />
    <style>
        .table-container {
            max-height: calc(100vh - 200px);
            overflow-y: scroll;
        }
    </style>
</head>
<body class="has-background-light">
<div class="container">
    {% block content %}
    <section class="section">
        <div class="columns is-vcentered">
            <div class="column is-half">
                <h1 class="title">Actions</h1>
            </div>
            <div class="column is-half">
                <nav class="breadcrumb is-right" aria-label="breadcrumbs">
                    <ul>
                        <li><a href="../../../">Home</a></li>
                        <li><a href="../">Customers</a></li>
                        <li class="is-active"><a href="#" aria-current="page">1</a></li>
                    </ul>
                </nav>
            </div>
        </div>
    </section>

    <section class="section">
        <div class="columns">
            <div class="column is-half">
                <div class="card">
                    <header class="card-header">
                        <p class="card-header-title">{{ main.name }}</p>
                    </header>
                    <div class="card-content">
                        <div class="content">
                            <p><strong>ID:</strong> {{ main.nr }}</p>
                            <p><strong>Saldo:</strong> {{ main.saldo }}</p>
                        </div>
                    </div>
                </div>
            </div>

            <div class="column is-half">
                <div class="card">
                    <header class="card-header">
                        <p class="card-header-title">Actions</p>
                        <ion-icon name="refresh-outline" id="refresh" style="float: right; font-size: 200%"></ion-icon>
                    </header>
                    <div class="card-content table-container">
                        <table class="table is-bordered">
                            <thead>
                            <tr>
                                <th>Action ID</th>
                                <th>Customer Number</th>
                                <th>Date</th>
                                <th>Action Type</th>
                                <th>Amount</th>
                                
                            </tr>
                            </thead>
                            <tbody>
                            {% if actions %}
                            {% for action in actions %}
                            <tr>
                                <td>{{ action.id }}</td>
                                <td>{{ action.nr }}</td>
                                <td>{{ action.datum }}</td>
                                <td>{{ action.get_type_display }}</td>
                                <td>{{ action.betrag }}</td>
                            </tr>
                            {% endfor %}
                            {% else %}
                            <td>No Action</td>
                            {% endif %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </section>
    {% endblock %}
</div>

<script src="{% static 'scripts.js' %}"></script>

<style>
    @keyframes spin {
        0% {
            transform: rotate(0deg);
        }
        100% {
            transform: rotate(360deg);
        }
    }

    .rotate-animation {
        animation: spin 1s linear infinite;
    }
</style>
</body>
</html>

Actions/templates/actions.html
<!DOCTYPE html>
<html>
  <head>
    <title>Action List</title>
    {% load static %}
    <!--<link rel="stylesheet" href="{% static 'style.css' %}" />-->
    <link
      rel="stylesheet"
      href="{% static 'adminlte/css/adminlte.min.css' %}"
    />
    <style>
      .table-container {
        max-height: calc(100vh - 200px);
        overflow-y: scroll;
      }
    </style>
  </head>
  <body class="hold-transition sidebar-mini">
    <div class="wrapper">
      {% block content %}
      <div class="content-header">
        <div class="container-fluid">
          <div class="row mb-2">
            <div class="col-sm-6">
              <h1>Actions</h1>
            </div>
            <div class="col-sm-6">
              <ol class="breadcrumb float-sm-right">
                <li class="breadcrumb-item"><a href="../../">Home</a></li>
                <li class="breadcrumb-item active">Actions</li>
              </ol>
            </div>
          </div>
        </div>
      </div>

      <section class="content">
        <div class="container-fluid">
          <div class="row">
            <div class="col-md-12">
              <div class="card">
                <div class="card-header">
                  <h3 class="card-title">Action List</h3>
                  <ion-icon
                    name="refresh-outline"
                    id="refresh"
                    style="float: right; font-size: 200%"
                  ></ion-icon>
                </div>
                <div class="card-body table-container">
                  <table class="table-bordered table">
                    <thead>
                      <tr>
                        <th>NR</th>
                        <th>Datum</th>
                        <th>Action Type</th>
                        <th>Betrag</th>
                        <th>Kunde ID</th>
                      </tr>
                    </thead>
                    <tbody>
                      {% for action in actions %}
                      <tr>
                        <td>{{ action.nr }}</td>
                        <td>{{ action.datum }}</td>
                        <td>{{ action.actionstyp }}</td>
                        <td>{{ action.betrag }}</td>
                        <td>{{ action.kunde_id }}</td>
                      </tr>
                      {% endfor %}
                    </tbody>
                  </table>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>
      {% endblock %}
    </div>

    <script src="{% static 'scripts.js' %}"></script>
    <script src="{% static 'adminlte/js/adminlte.min.js' %}"></script>
    <script
      type="module"
      src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.esm.js"
    ></script>
    <script
      nomodule
      src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.js"
    ></script>

    <style>
      @keyframes spin {
        0% {
          transform: rotate(0deg);
        }
        100% {
          transform: rotate(360deg);
        }
      }

      .rotate-animation {
        animation: spin 1s linear infinite;
      }
    </style>
  </body>
</html>

Actions/templates/customer.html
<!DOCTYPE html>
<html>
<head>
    <title>Customer ({{main.nr}}/{{main.customer}})</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'style.css' %}" />
    <style>
        .table-container {
            max-height: calc(100vh - 200px);
            overflow-y: scroll;
        }
    </style>
</head>
<body class="has-background-light">
<div class="container">
    {% block content %}
    <section class="section">
        <div class="columns is-vcentered">
            <div class="column is-half">
                <h1 class="title">Customers</h1>
            </div>
            <div class="column is-half">
                <nav class="breadcrumb is-right" aria-label="breadcrumbs">
                    <ul>
                        <li><a href="../../../">Home</a></li>
                        <li><a href="../">Customers</a></li>
                        <li class="is-active"><a href="#" aria-current="page">1</a></li>
                    </ul>
                </nav>
            </div>
        </div>
    </section>

    <section class="section">
        <div class="columns">
            <div class="column is-half">
                <div class="card">
                    <header class="card-header">
                        <p class="card-header-title">{{ main.name }}</p>
                    </header>
                    <div class="card-content">
                        <div class="content">
                            <p><strong>ID:</strong> {{ main.nr }}</p>
                            <p><strong>Saldo:</strong> {{ main.saldo }}</p>
                        </div>
                    </div>
                </div>
            </div>

            <div class="column is-half">
                <div class="card">
                    <header class="card-header">
                        <p class="card-header-title">Actions</p>
                        <ion-icon name="refresh-outline" id="refresh" style="float: right; font-size: 200%"></ion-icon>
                    </header>
                    <div class="card-content table-container">
                        <table class="table is-bordered">
                            <thead>
                            <tr>
                                <th>Action ID</th>
                                <th>Customer Number</th>
                                <th>Date</th>
                                <th>Action Type</th>
                                <th>Amount</th>
                            </tr>
                            </thead>
                            <tbody>
                            {% if actions %}
                            {% for action in actions %}
                            <tr>
                                <td>{{ action.id }}</td>
                                <td>{{ action.nr }}</td>
                                <td>{{ action.date }}</td>
                                <td>{{ action.actiontype }}</td>
                                <td>{{ action.betrag }}</td>
                            </tr>
                            {% endfor %}
                            {% else %}
                            <td>No Action</td>
                            {% endif %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </section>
    {% endblock %}
</div>

<script src="{% static 'scripts.js' %}"></script>

<style>
    @keyframes spin {
        0% {
            transform: rotate(0deg);
        }
        100% {
            transform: rotate(360deg);
        }
    }

    .rotate-animation {
        animation: spin 1s linear infinite;
    }
</style>
</body>
</html>

Actions/templates/customers.html
<!DOCTYPE html>
<html>
  <head>
    <title>Customer List</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'style.css' %}" />
    <style>
      .table-container {
        max-height: calc(100vh - 200px);
        overflow-y: scroll;
      }
    </style>
  </head>
  <body class="hold-transition sidebar-mini">
    <div class="wrapper">
      {% block content %}
      <div class="content-header">
        <div class="container-fluid">
          <div class="row mb-2">
            <div class="col-sm-6">
              <h1>Customers</h1>
            </div>
            <div class="col-sm-6">
              <ol class="breadcrumb float-sm-right">
                <li class="breadcrumb-item"><a href="../../">Home</a></li>
                <li class="breadcrumb-item active">Customers</li>
              </ol>
            </div>
          </div>
        </div>
      </div>

      <section class="content">
        <div class="container-fluid">
          <div class="row">
            <div class="col-md-12">
              <div class="card">
                <div class="card-header">
                  <h3 class="card-title">Customer List</h3>
                  <ion-icon
                    name="refresh-outline"
                    id="refresh"
                    style="float: right; font-size: 200%"
                  ></ion-icon>
                </div>
                <div class="card-body table-container">
                  <table class="table-bordered table">
                    <thead>
                      <tr>
                        <th>Customer Number</th>
                        <th>Name</th>
                        <th>Saldo</th>
                      </tr>
                    </thead>
                    <tbody>
                      {% for customer in customers %}
                      <tr onclick="customerDet({{customer.nr}})">
                        <td>{{ customer.nr }}</td>
                        <td>{{ customer.name }}</td>
                        <td>{{ customer.saldo }}</td>
                      </tr>
                      {% endfor %}
                    </tbody>
                  </table>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>
      {% endblock %}
    </div>

    <script src="{% static 'scripts.js' %}"></script>
    <script src="{% static 'adminlte/js/adminlte.min.js' %}"></script>
    <script
      type="module"
      src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.esm.js"
    ></script>
    <script
      nomodule
      src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.js"
    ></script>

    <style>
      @keyframes spin {
        0% {
          transform: rotate(0deg);
        }
        100% {
          transform: rotate(360deg);
        }
      }

      .rotate-animation {
        animation: spin 1s linear infinite;
      }
    </style>
  </body>
</html>

Actions/templates/dashboard.html
<!DOCTYPE html>
<html>
  <head>
    <title>StadtBank</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'style.css' %}" />
    <link rel="icon" type="image/ico" href="{% static 'favicon.ico' %}" />
  </head>
  <body>
    <nav
      class="navbar is-primary"
      role="navigation"
      aria-label="main navigation"
    >
      <div class="navbar-brand">
        <a class="navbar-item" href="#"> Dashboard </a>
      </div>
      <div class="navbar-end">
        <div id="breadcrumb" class="navbar-item">
          <nav class="breadcrumb" aria-label="breadcrumbs">
            <ul>
              <li class="is-active">
                <a href="#">
                  <span class="icon is-small">
                    <i class="fas fa-home" aria-hidden="true"></i>
                  </span>
                  <span>Home</span>
                </a>
              </li>
            </ul>
          </nav>
        </div>
      </div>
    </nav>

    <section class="section">
      <div class="container">
        <div class="columns">
          <div class="column is-half">
            <div class="card" style="max-height: calc(100vh - 150px); overflow-y: scroll">
              <header class="card-header">
                <p class="card-header-title">Customer List</p>
                <a href="#" class="card-header-icon" aria-label="refresh">
                  <i class="fas fa-sync"></i>
                </a>
              </header>
              <div class="card-content">
                <div class="table-container">
                  <table class="table is-bordered is-fullwidth">
                    <thead>
                      <tr>
                        <th>Customer Number</th>
                        <th>Name</th>
                        <th>Saldo</th>
                      </tr>
                    </thead>
                    <tbody>
                      {% if customers %} {% for customer in customers %}
                      <tr onclick="customerDetails({{customer.nr}})">
                        <td>{{ customer.nr }}</td>
                        <td>{{ customer.name }}</td>
                        <td>{{ customer.balance }}</td>
                      </tr>
                      {% endfor %} {% else %}
                      <td colspan="3">No Customer</td>
                      {% endif %}
                    </tbody>
                  </table>
                </div>
              </div>
            </div>
          </div>

          <div class="column is-half">
            <div class="card" style="max-height: calc(100vh - 150px); overflow-y: scroll">
              <header class="card-header">
                <p class="card-header-title">Actions</p>
                <a href="#" class="card-header-icon" aria-label="refresh">
                  <i class="fas fa-sync"></i>
                </a>
              </header>
              <div class="card-content">
                <div class="table-container">
                  <table class="table is-bordered is-fullwidth">
                    <thead>
                      <tr>
                        <th>Action ID</th>
                        <th>Customer Number</th>
                        <th>Date</th>
                        <th>Action Type</th>
                        <th>Amount</th>
                        <th>Releated</th>
                      </tr>
                    </thead>
                    <tbody>
                      {% if actions %} {% for action in actions %}
                      <tr onclick="actionDetails({{action.id}})">
                        <td>{{ action.id }}</td>
                        <td>{{ action.nr }}</td>
                        <td>{{ action.date|date:"j M" }}</td>
                        <td>{{ action.type}}</td>
                        <td>{{ action.amount }}</td>
                        <td>{{ action.related_nr|default:"-"  }}</th>
                      </tr>
                      {% endfor %} {% else %}
                      <td colspan="6">No Action</td>
                      {% endif %}
                    </tbody>
                  </table>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>

    <script src="{% static 'scripts.js' %}"></script>
  </body>
</html>

Actions/templates/settings.html
<!DOCTYPE html>
<html>
  <head>
    <title>StadtBank</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'style.css' %}" />
    <link rel="icon" type="image/ico" href="{% static 'favicon.ico' %}" />
  </head>
  <body>
    <nav
      class="navbar is-primary"
      role="navigation"
      aria-label="main navigation"
    >
      <div class="navbar-brand">
        <a class="navbar-item" href="#"> Settings </a>
      </div>
      <div class="navbar-end">
        <div id="breadcrumb" class="navbar-item">
          <nav class="breadcrumb" aria-label="breadcrumbs">
            <ul>
              <li>
                <a href="..">
                  <span class="icon is-small">
                    <i class="fas fa-home" aria-hidden="true"></i>
                  </span>
                  <span>Home</span>
                </a>
              </li>
              <li class="is-active">
                <a href="#">
                  <span class="icon is-small">
                    <i class="fas fa-gear" aria-hidden="true"></i>
                  </span>
                  <span>Settings</span>
                </a>
              </li>
            </ul>
          </nav>
        </div>
      </div>
    </nav>

    <div class="container is-max-desktop">
  <div class="tabs is-boxed">
    <ul>
      <li class="is-active"><a>System</a></li>
      <li><a >User</a></li>
    </ul>
  </div>
  <div id="tab-content">
    <div class="tab-content">
      <div class="container">
        <label class="label">Program Settings</label>
        <div class="field">
          <label class="label">IP Address</label>
          <div class="control has-icons-left">
            <input class="input" type="text" placeholder="X.X.X.X"/>
            <span class="icon is-small is-left">
              <i class="fas fa-globe"></i>
            </span>
          </div>
        </div>
      </div>
    </div>
    <div class="tab-content is-hidden" id="user-tab">Content for User</div>
  </div>
</div>


    <script src="{% static 'scripts.js' %}"></script>
  </body>
</html>